function X =  problem045
% Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
% Triangle 	  	T_(n)=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
% Pentagonal 	  	P_(n)=n(3n?1)/2 	  	1, 5, 12, 22, 35, ...
% Hexagonal 	  	H_(n)=n(2n?1) 	  	1, 6, 15, 28, 45, ...
% It can be verified that T_(285) = P_(165) = H_(143) = 40755. 
% Find the next triangle number that is also pentagonal and hexagonal.
j = 1;
n3 = 144;
while j ~= 0
    n2 = 1/6*(sqrt(48*n3^2 - 24*n3 + 1) + 1);
    if floor(n2) == n2
        %n1 = 1/2*(sqrt(12*n2^2 - 4*n2 +1) -1);
        %if floor(n1) == n1
            %j = 0;
            X = [ n3 n2]
            keyboard
            j = 0;
        %end
    end
    n3 = n3+1;
end
