function sum_fibo = problem2(X)
%Each new term in the Fibonacci sequence is generated by 
%adding the previous two terms. By starting with 1 and 2, 
%the first 10 terms will be:
%1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%Find the sum of all the even-valued terms in the sequence 
%which do not exceed four million.( or X in general)
j1 = 1;
j2 = 2;
j3 = 3;
sum_fibo = 2;
while j3 <= X
    j3 = j2 + j1;
    if rem(j3,2) == 0
        sum_fibo = sum_fibo + j3;
    end
    j1 = j2;
    j2 = j3;
end