function total = problem029(n)
%How many distinct terms are in the sequence generated by a^(b) 
%for 2 <= a <=100 and 2 <= b <= 100
% or in general 100 replaced by n
s = 0;
for a = 2:n
    k = 1;
    while a^k <= n
        k = k +1;
    end
    
    for i = 3:(k-1)
        s = s + floor((n-2)/i)s;
    end
end

total = (n-1)^2 - s;